version: '3'

services:
  web:
    image: nginx:1.19.10-alpine
#    image: nginx:1.19.10
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./public_html:/public_html
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - nginxphp
  php:
#    image: php:7.4.16-fpm-alpine
    image: php:8.0.3-fpm-alpine
#    image: php:8.0.3-fpm
    container_name: php
    volumes:
      - ./public_html:/public_html
    expose:
      - 9000
    networks:
      - nginxphp

networks:
  nginxphp: